### ISSUE TITLE
Site not updating with spotlight information

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Spotlight#1]
I have created a sample spotlight, but when i publish and preview nothing is showing up?

Thanks!

**Comment by banksashleym** [comment]
Oh I'm a dummy, I didn't see the featured star :) I clicked that and now it's showing up on the homepage. But when i click the "learn more" link it goes to a 404 page.

**Comment by joelworsham** [comment]
Right, sorry about that. I needed to flush the permalinks after activating the plugin. All set now.

**Comment by banksashleym** [comment]
Awesome, thank you! 
Sorry, just one more thing...could you also make the spotlights visible in the widgets area so that I'm able to add the archives to the side bar and style it with the drop down (like I'm able to do with the news/events)...I'd like the spotlights to look very similar to how we have done the news section where there is a drop down for spotlight archives.

Also, in the burgundy bar could we just say "Jackson College Spotlight" for each spotlight instead of the page title for each spotlight?

Thanks!!

**Comment by joelworsham** [comment]
Sure thing. See #2.
