### ISSUE TITLE
Make spotlight area consistent title / banner / sidebar like other sections

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Spotlight#2]
"Sorry, just one more thing...could you also make the spotlights visible in the widgets area so that I'm able to add the archives to the side bar and style it with the drop down (like I'm able to do with the news/events)...I'd like the spotlights to look very similar to how we have done the news section where there is a drop down for spotlight archives.

Also, in the burgundy bar could we just say "Jackson College Spotlight" for each spotlight instead of the page title for each spotlight?

Thanks!!"

**Comment by joelworsham** [comment]
@banksashleym Also, do you want the banner to be consistent? Like with other sections?

**Comment by banksashleym** [comment]
Yes, please!
