### ISSUE TITLE
Possible for no spotlight set even when some are featured

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Spotlight#3]
Not sure the conditions that caused it.

**Comment by joelworsham** [comment]
@banksashleym 

It seems that there's a featured spotlight with no featured image set. http://jacksoncollege.staging.wpengine.com/wp-admin/post.php?post=7837&action=edit

I'm fairly confident this is why no image was present.

I think it would be wise to setup a soft fallback, so that if there's no spotlight available (which should never happen, but it's possible it could), there's at least something there.

Do you have a good, generic image that we could place in there as a backup?

**Comment by banksashleym** [comment]
Oh wow, I'm not even sure how that one got featured...sorry about that! Yes, i will go through our images and find a generic one. Thanks!

**Comment by joelworsham** [comment]
No problem! Once you find that image, simply upload it in the new issue JacksonCollege/Primary-Theme#117 and I'll set it up.
